# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake-3.21.3-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake-3.21.3-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yuzhaoxi/javaprofileragent

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yuzhaoxi/javaprofileragent

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake-3.21.3-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake-3.21.3-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuzhaoxi/javaprofileragent/CMakeFiles /home/yuzhaoxi/javaprofileragent//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuzhaoxi/javaprofileragent/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named attach-myagent

# Build rule for target.
attach-myagent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attach-myagent
.PHONY : attach-myagent

# fast build rule for target.
attach-myagent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attach-myagent.dir/build.make CMakeFiles/attach-myagent.dir/build
.PHONY : attach-myagent/fast

#=============================================================================
# Target rules for targets named jpa

# Build rule for target.
jpa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jpa
.PHONY : jpa

# fast build rule for target.
jpa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpa.dir/build.make CMakeFiles/jpa.dir/build
.PHONY : jpa/fast

src/javaprofileragent.o: src/javaprofileragent.cpp.o
.PHONY : src/javaprofileragent.o

# target to build an object file
src/javaprofileragent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpa.dir/build.make CMakeFiles/jpa.dir/src/javaprofileragent.cpp.o
.PHONY : src/javaprofileragent.cpp.o

src/javaprofileragent.i: src/javaprofileragent.cpp.i
.PHONY : src/javaprofileragent.i

# target to preprocess a source file
src/javaprofileragent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpa.dir/build.make CMakeFiles/jpa.dir/src/javaprofileragent.cpp.i
.PHONY : src/javaprofileragent.cpp.i

src/javaprofileragent.s: src/javaprofileragent.cpp.s
.PHONY : src/javaprofileragent.s

# target to generate assembly for a file
src/javaprofileragent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpa.dir/build.make CMakeFiles/jpa.dir/src/javaprofileragent.cpp.s
.PHONY : src/javaprofileragent.cpp.s

src/javaprofilerfile.o: src/javaprofilerfile.cpp.o
.PHONY : src/javaprofilerfile.o

# target to build an object file
src/javaprofilerfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpa.dir/build.make CMakeFiles/jpa.dir/src/javaprofilerfile.cpp.o
.PHONY : src/javaprofilerfile.cpp.o

src/javaprofilerfile.i: src/javaprofilerfile.cpp.i
.PHONY : src/javaprofilerfile.i

# target to preprocess a source file
src/javaprofilerfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpa.dir/build.make CMakeFiles/jpa.dir/src/javaprofilerfile.cpp.i
.PHONY : src/javaprofilerfile.cpp.i

src/javaprofilerfile.s: src/javaprofilerfile.cpp.s
.PHONY : src/javaprofilerfile.s

# target to generate assembly for a file
src/javaprofilerfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpa.dir/build.make CMakeFiles/jpa.dir/src/javaprofilerfile.cpp.s
.PHONY : src/javaprofilerfile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... attach-myagent"
	@echo "... jpa"
	@echo "... src/javaprofileragent.o"
	@echo "... src/javaprofileragent.i"
	@echo "... src/javaprofileragent.s"
	@echo "... src/javaprofilerfile.o"
	@echo "... src/javaprofilerfile.i"
	@echo "... src/javaprofilerfile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

